//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gym2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Venta = new HashSet<Venta>();
        }
    
        public int id { get; set; }

        [Required(ErrorMessage = "Campo obligatorio")]
        [RegularExpression("[0-9]{8}[0-9kK]{1}$", ErrorMessage = "Rut incorrecto")]
        public string rut { get; set; }

        [Required(ErrorMessage = "Campo obligatorio")]
        [RegularExpression("[A-Za-z]*", ErrorMessage = "Debe contener solo letras")]
        public string nombres { get; set; }

        [Required(ErrorMessage = "Campo obligatorio")]
        [RegularExpression("[A-Za-z]*", ErrorMessage = "Debe contener solo letras")]
        public string apellidos { get; set; }

        [Required(ErrorMessage = "Campo obligatorio")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:YYYY-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime fech_nacimiento { get; set; }

        [Required(ErrorMessage = "Campo obligatorio")]
        [RegularExpression("[0-9]*", ErrorMessage = "Solo se permite números")]
        [StringLength(maximumLength: 9, MinimumLength = 9, ErrorMessage = "Debe contener 9 digitos")]
        public string telefono { get; set; }

        [Required(ErrorMessage = "Campo obligatorio")]
        public string direccion { get; set; }

        [Required(ErrorMessage = "Campo obligatorio")]
        [EmailAddress(ErrorMessage = "Email incorrecto")]
        public string email { get; set; }

        public string password { get; set; }
        public int idRol { get; set; }
        public string token { get; set; }
    
        public virtual Rol Rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta> Venta { get; set; }
    }
}
